variable "sns_topic_name" {
  description = "The friendly name for the SNS topic. By default generated by Terraform"
}
variable "sns_topic_min_delay_target" {
  description = "The sns_topic_min_delay_target"
}
variable "sns_topic_max_delay_target" {
  description = "The sns_topic_max_delay_target"
}
variable "sns_topic_num_retries" {
  description = "The sns_topic_num_retries"
}
variable "sns_topic_num_max_delay_retries" {
  description = "The sns_topic_num_max_delay_retries"
}
variable "sns_topic_num_no_delay_retries" {
  description = "The sns_topic_num_no_delay_retries"
}
variable "sns_topic_num_min_delay_retries" {
  description = "The sns_topic_num_min_delay_retries"
}
variable "sns_topic_backoff_function" {
  description = "The sns_topic_backoff_function"
}
variable "sns_topic_disable_subscription_overrides" {
  description = "The sns_topic_disable_subscription_overrides"
}
variable "sns_topic_max_receives_per_second" {
  description = "The sns_topic_max_receives_per_second"
}